services:
  postgres_customer:
    container_name: postgres_customer
    image: postgres
    environment:
      POSTGRES_USER: twaincards
      POSTGRES_PASSWORD: twaincards
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_customer:/var/lib/postgresql/data
    networks:
      - postgres_customer
  postgres_notification:
    container_name: postgres_notification
    image: postgres
    environment:
      POSTGRES_USER: twaincards
      POSTGRES_PASSWORD: twaincards
      POSTGRES_DB: notification
    ports:
      - "5433:5432"
    volumes:
      - postgres_notification:/var/lib/postgresql/data
    networks:
      - postgres_notification
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pgadmin
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

networks:
  postgres_notification:
    driver: bridge
  postgres_customer:
    driver: bridge
  spring:
    driver: bridge
  pgadmin:
    driver: bridge

volumes:
  postgres_customer:
  postgres_notification:
  pgadmin: